### ISSUE TITLE
Report is not meaningful when module has symlinked to `node_modules/.store`

### ISSUE THREAD

**Issue by ratson** [robertknight/webpack-bundle-size-analyzer#12]
I have recently switched to [pnpm](https://github.com/rstacruz/pnpm) for faster `npm install`, which rely on symlink moduels under `node_modules/.store`.

Unfortunately, this makes `webpack-bundle-size-analyzer` report less useful. Hope support for this use case could be added.

**Comment by robertknight** [comment]
npm installation performance improved significantly since this report was filed, and yarn came along as well. On that basis I'm going to close this as "solved", albeit indirectly. Please let me know if this is still a problem for you.
