### ISSUE TITLE
Unexpected token r in JSON at position 0

### ISSUE THREAD

**Issue by cortopy** [robertknight/webpack-bundle-size-analyzer#13]
When running `webpack --json | webpack-bundle-size-analyzer` webpack starts compiling and after finishing I get the following error:

```
SyntaxError: Unexpected token r in JSON at position 0
    at Object.parse (native)
    at printStats (/home/me/.opt/npm/lib/node_modules/webpack-bundle-size-analyzer/build/cli.js:6:28)
    at Socket.<anonymous> (/home/me/.opt/npm/lib/node_modules/webpack-bundle-size-analyzer/build/cli.js:20:50)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:458:13)
```

I suspect this is something to do with the JSON parser of webpack-bundle-size-analyzer. I've tried different webpack configs and sometimes instead of `r` is a `>`. Not sure how to debug this.

**Comment by robertknight** [comment]
Hello @cortopy - Can you post the output of `webpack --json`.

**Comment by cortopy** [comment]
@robertknight The json file came out as a beast of 78810 lines. But looking at the first two lines just made me realised what the problem was.
I have one `console.log` in my webpack.config and I use [webpack-validator ](https://github.com/js-dxtools/webpack-validator), which in turn also logs the result of the validation
Removing those two lines solved the issue. I do not know why webpack includes them, as they clearly invalidate any json schema

I guess that's what I'll have to do, but I'm wondering if the parser could not ignore any logging information before the actual json object itself

**Comment by robertknight** [comment]
> I guess that's what I'll have to do, but I'm wondering if the parser could not ignore any
> logging information before the actual json object itself

The tool does not know which of the output is logging and which is JSON. If you use `console.error` the logging output will be written to `process.stderr` instead of `process.stdout` and you can then direct it to a separate place than the JSON output.
