### ISSUE TITLE
not working on windows?

### ISSUE THREAD

**Issue by flyon** [robertknight/webpack-bundle-size-analyzer#14]
If I run `webpack --json | webpack-bundle-size-analyzer` in my windows terminal nothing happens?

I try to save the stats to stats.json and then run it with `webpack-bundle-size-analyzer stats.json` but that gives me `SyntaxError: Unexpected token T`

**Comment by robertknight** [comment]
The first thing to check is that the `stats.json` file is actually valid JSON. If it is, can you please post the contents of the `stats.json` file?

**Comment by robertknight** [comment]
> If I run webpack --json | webpack-bundle-size-analyzer in my windows terminal nothing happens?

I don't have a Windows environment set up to test at the moment, so help from someone who does would be appreciated. `webpack-bundle-stats-analyzer` should read JSON from stdin if available.

**Comment by robertknight** [comment]
I'm closing this as there hasn't been a response to my earlier question. I'll reopen if you can provide more details.

**Comment by hedgehog34** [comment]
Can't make it working on my Windows machine.  After `webpack --json | webpack-bundle-size-analyzer` I'm getting 

```
Output filename not configured
undefined:1

SyntaxError: Unexpected token b
...
```

error. 

Although running `webpack --json` only outputs (enormous) stream of data spits out to the console in the form of a json. Is it that Windows doesn't like the `|` symbol?

How can I help in debunking this problem?
