### ISSUE TITLE
what's the self mean in the outputted file?

### ISSUE THREAD

**Issue by ghost** [robertknight/webpack-bundle-size-analyzer#17]
Below is the output of my bundle.js .
**lodash: 708.39 KB (13.3%)
react: 606.47 KB (11.4%)
ssc-cdt3: 498.73 KB (9.35%)
react-bootstrap: 340.45 KB (6.38%)
  core-js: 7.33 KB (2.15%)
  babel-runtime: 2.54 KB (0.746%)
  <self>: 330.58 KB (97.1%)**

The react-bootstrap is about 340.45 KB, but what's core-js and why it's indented against react-bootstrap?
And I don't totally understand the sentence it the official document below.
**<self> refers to the size of the bundle's own code.**.
What does it mean by 'own code'?

**Comment by stretchkennedy** [comment]
> what's core-js and why it's indented against react-bootstrap?

It's a dependency of babel-runtime, and babel-runtime is a dependency of react-bootstrap.

> What does it mean by 'own code'?

As I understand it, any part of your bundle that isn't an npm module. If you're writing an app, it means the size of your app.

**Comment by robertknight** [comment]
> As I understand it, any part of your bundle that isn't an npm module.
> If you're writing an app, it means the size of your app.

This is correct. It refers to the size of the bundle's code excluding any dependencies.
