### ISSUE TITLE
Recommend sorting the output in the README

### ISSUE THREAD

**Issue by ericclemmons** [robertknight/webpack-bundle-size-analyzer#18]
This makes it easier to grok:

``` shell
$> webpack --json --sort-modules-by size | webpack-bundle-size-analyzer
```

**Comment by robertknight** [comment]
Thank-you for the suggestion! I think I'm missing something - `webpack-bundle-size-analyzer` already sorts its dependencies in size order when printing the dependency tree, so this flag shouldn't affect the output.

**Comment by ericclemmons** [comment]
Oh, weird.  I must've misread the output or something.  I _assumed_ it did, but _thought_ I got different results :D

Closing since I made a mistake.

Thanks!
