### ISSUE TITLE
Cli pipe usage is currently broken

### ISSUE THREAD

**Issue by chiawendt** [robertknight/webpack-bundle-size-analyzer#43]
node v9.4.0
webpack 3.10.0

The cli does not seem to get the stdin by
`webpack --json | webpack-bundle-size-analyzer`.
On the other hand the following works.
`webpack --json > /tmp/1 && webpack-bundle-size-analyzer /tmp/1`.

**Comment by robertknight** [comment]
I've just tested this locally with node v9.4.0 and was not able to reproduce. Can you clarify what happens when you try running `webpack --json | webpack-bundle-size-analyzer`? Can you also confirm which platform you are using (Windows, macOS, Linux)?

**Comment by chiawendt** [comment]
Sorry, this issue is a total mistake. I confused this project with "webpack-bundle-analyzer".
