### ISSUE TITLE
Unknown command 'webpack'

### ISSUE THREAD

**Issue by mesqueeb** [robertknight/webpack-bundle-size-analyzer#44]
I get
> Unknown command 'webpack'

Should webpack maybe be added as dependancy to `webpack-bundle-size-analyzer`?

**Comment by robertknight** [comment]
`webpack-bundle-size-analyzer` analyzes the _JSON output_ from a Webpack build, it doesn't directly _use_ Webpack itself, so it is not a dependency.

If you have only installed Webpack locally in your project and not globally (eg. with `npm install -g`) then the command to invoke Webpack will be slightly different than the example given in the README: `./node_modules/.bin/webpack --json | webpack-bundle-size-analyzer`. Is this the problem you ran into?

**Comment by mesqueeb** [comment]
@robertknight thanks for your kind words. I'm trying to use in with a framework (quasar) that uses webpack under the hood. But i'm not sure how.
