### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by attilapuskas** [robertknight/webpack-bundle-size-analyzer#47]
We have noticed that with webpack 4 there is a DeprecationWarning for the plugin.

```
DeprecationWarning: Tapable.plugin is deprecated. Use new API on ``.hooks`` instead`
`at WebpackBundleSizeAnalyzerPlugin.apply (.\node_modules\webpack-bundle-size-analyzer\build\src\plugin.js:15:18)
```

According to that [comment](https://github.com/webpack/webpack/issues/6568#issuecomment-377491754) the changes should be done here.

**Comment by robertknight** [comment]
Thank-you for the report and the discussion link. I'm not actively using webpack for work at the moment, so I can't promise when I'll get to this. I will take a look at any PRs that are submitted for it.

**Comment by spiltcoffee** [comment]
@robertknight pretty easy fix, just changed stats.plugin('done') to stats.hooks.done.tap()

Confirmed it worked on my own Webpack 4 project.

**Comment by spiltcoffee** [comment]
@robertknight any word on #48 being merged?
