### ISSUE TITLE
Module size in SI units

### ISSUE THREAD

**Issue by lexaurin** [robertknight/webpack-bundle-size-analyzer#6]
Webpack shows size in SI bytes (power of 1000), analyzer should also. 
https://github.com/webpack/webpack/blob/master/lib/Stats.js#L397
Otherwise it's confusing.

**Comment by robertknight** [comment]
Reflecting on this, I think I'd rather use units which match all of the rest of the development tools I use, even if that means being inconsistent with Webpack, and would rather suggest at least asking Webpack to consider changing to non-SI units.

**Comment by x2es** [comment]
Size of file shows number of bits needed to store/transfer it's content. That's why 2^10 have exact meaning, while 10^3 tells nothing.

This days development (especially JS) gone far from Computer Since. Today's approaches and tools looks as more Lego Since rather Computer Since.
